[package]
name = "ngspf"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ngsbase = { path = "../ngsbase" }
ngspf_core = { path = "src/core" }
ngspf_viewport = { path = "src/viewport" }
ngspf_com = { path = "src/com" }

[dev-dependencies]
rand = "0.3.16"
cgmath = "0.15.0"
