[package]
name = "ngspf"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ngsgfx = { path = "../ngsgfx" }
arclock = { path = "../support/arclock" }
refeq = { path = "../support/refeq" }
tokenlock = { path = "../support/tokenlock" }
iterpool = { path = "../support/iterpool" }
cgmath = "0.15.0"
winit = "0.7"
enumflags = "*"
enumflags_derive = "*"
atomic_refcell = "0.1.0"
