[package]
name = "ngspf"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ngsgfx = { path = "../ngsgfx" }
ngsbase = { path = "../ngsbase" }
arclock = { path = "../support/arclock" }
refeq = { path = "../support/refeq", features = ["nightly"] }
tokenlock = { path = "../support/tokenlock" }
iterpool = { path = "../support/iterpool" }
ngsenumflags = { path = "../support/ngsenumflags" }
ngsenumflags_derive = { path = "../support/ngsenumflags/ngsenumflags_derive" }
cgmath = "0.15.0"
winit = "0.7"
atomic_refcell = "0.1.0"
