[package]
name = "zangfx_spirv-cross"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
libc = "0.2.7"
unsafe_unions = "0.0.2"

[build-dependencies]
cc = "1.0.3"
prebuild-glslang = { path = "../../../../../../support/prebuild-glslang" }

[dev-dependencies]
include_data = { path = "../../../../../../support/include_data" }