[package]
name = "zangfx_metal-rs"
version = "0.3.0"
description = "Rust bindings for Metal"
authors = ["metal-rs authors", "yvt"]
readme = "README.md"
keywords = ["metal", "graphics", "bindings"]
license = "MIT OR Apache-2.0"

[dependencies]
cocoa = "0.9"
bitflags = "0.7"
libc = "0.2"
objc-foundation = "0.1"
block = "0.1.5"
fast_msg_send = { path = "../../../../../../support/fast_msg_send" }

[dependencies.objc]
version = "0.2.1"
features = ["objc_exception"]

