[package]
name = "enet-ll"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
libc = "0.2.7"
ngsenumflags = { path = "../support/ngsenumflags" }
ngsenumflags_derive = { path = "../support/ngsenumflags/ngsenumflags_derive" }

[build-dependencies]
cc = "1.0.3"
