[package]
name = "ngsgfx_wsi_metal"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
cocoa = "0.8"
objc = "0.2"
cgmath = "0.14.1"
ngsgfx_core = { path = "../../core" }
ngsgfx_metal = { path = "../../backend/metal"}
ngsgfx_wsi_core = { path = "../../wsi_core" }
