[package]
name = "ngsenumflags_derive"
version = "0.2.2"
authors = ["maik klein <maikklein@googlemail.com>", "yvt <i@yvt.jp>"]
description = "Bitflags (based on 'enumflags')"

[dependencies]
syn = "0.11.4"
quote = "0.3.12"

[lib]
proc-macro = true
