[package]
name = "ysr2_common"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
xdispatch = { path = "../../../xdispatch", optional = true }
num_cpus = "1.0"
cgmath = "0.14.1"
simd = "0.2.0"
atomic_refcell = "0.1.0"
arrayvec = "0.4.1"
