#include "nsISupports.idl"
#include "Interop/Types.idl"

[scriptable, uuid(29e48ae6-bb78-44b3-ba1d-5a3310ff137d)]
interface IVoxelTerrain : nsISupports
{
    readonly attribute long Width;
    readonly attribute long Height;
    readonly attribute long Depth;

    ngsTerrainVoxelInfo GetVoxel(in ngsIntVector3 voxel);
    void SetVoxel(in ngsIntVector3 voxel, in ngsTerrainVoxelInfo info);
};
