[package]
name = "zangfx_metal"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
zangfx_common = { path = "../../common" }
zangfx_base = { path = "../../base" }
zangfx_metal-rs = { path = "src/metal-rs"}
ngsenumflags = { path = "../../../../support/ngsenumflags" }
zangfx_spirv-cross = { path = "src/spirv-cross" }
block = "0.1.5"
rspirv = "0.5.1"
spirv_headers = "1.1.5"
cocoa = "0.15"
parking_lot = "0.5.5"
tokenlock = { path = "../../../../support/tokenlock" }
iterpool = { path = "../../../../support/iterpool" }
refeq = { path = "../../../../support/refeq" }
xalloc = { path = "../../../../support/xalloc-rs", features = ["nightly"] }
arrayvec = "0.4.1"
atomic_refcell = "0.1.3"

[dev-dependencies]
zangfx_test = { path = "../../test" }
