[package]
name = "ngsgfx_metal"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ngsgfx_core = { path = "../../core" }
ngsgfx_metal-rs = { path = "src/metal-rs"}
spirv-cross = { path = "src/spirv-cross" }
enumflags = "*"
cgmath = "0.14.1"
atomic_refcell = "0.1.0"
block = "0.1.5"
rspirv = "0.4.0"
