[package]
name = "ngsgfx_metal"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ngsgfx_core = { path = "../../core" }
ngsgfx_metal-rs = { path = "src/metal-rs"}
enumflags = "*"
cgmath = "*"
atomic_refcell = "0.1.0"
