//
// Copyright 2017 yvt, all rights reserved.
//
// This source code is a part of Nightingales.
//
//! NgsCOM bridges to [NgsPF](../ngspf/index.html).
extern crate atomic_refcell;
extern crate cgmath;
extern crate rgb;
extern crate arclock;
extern crate owning_ref;
extern crate send_cell;
extern crate stickylock;
extern crate tokenlock;

extern crate cggeom;
extern crate ngsbase;
#[macro_use]
extern crate ngscom;
extern crate ngspf_canvas as canvas;
extern crate ngspf_core as core;
extern crate ngspf_viewport as viewport;

mod context;
mod image;
mod nodes;
mod painter;
pub mod text;
mod workspace;

pub use ngsbase::{
    INgsPFContext, INgsPFLayer, INgsPFNodeGroup, INgsPFWindow, INgsPFWindowListener,
    INgsPFWorkspace,
};

pub use context::{ComContext, ProducerFrameLockGuard, ProducerFrameRefMut};
pub use image::{ComBitmap, ComImage};
pub use nodes::{INodeRef, INodeRefTrait};
pub use painter::ComPainter;
pub use workspace::ComWorkspace;

use std::ops::{Deref, DerefMut};

/// `HResult` values generated by NgsPF.
///
/// ## References
///
/// - [Structure of COM Error Codes]
///
/// [Structure of COM Error Codes]: https://msdn.microsoft.com/en-us/library/windows/desktop/ms690088(v=vs.85).aspx
///
pub mod hresults {
    use ngscom::HResult;

    /// Unable to modify a property because the node is already materialized.
    pub const E_PF_NODE_MATERIALIZED: HResult = HResult(0x80410001u32 as i32);

    /// Specified object is not a node, or originates from a different context.
    pub const E_PF_NOT_NODE: HResult = HResult(0x80410002u32 as i32);

    /// The object is currently in use by another thread.
    pub const E_PF_LOCKED: HResult = HResult(0x80410003u32 as i32);

    /// The object is not owned by the current thread.
    pub const E_PF_THREAD: HResult = HResult(0x80410004u32 as i32);

    /// Specified object is not an image.
    pub const E_PF_NOT_IMAGE: HResult = HResult(0x80410005u32 as i32);
}
