[package]
name = "ngscom"
version = "0.1.0"

authors = ["yvt <i@yvt.jp>"]
# license = "MIT"
readme = "README.md"

[dependencies]
libc = { version = "0.2.21" }
field-offset = { version = "0.1.1" }
lazy_static = { version = "0.2" }
