[package]
name = "ngsgfx_vulkan"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ngsgfx_core = { path = "../../core" }
cgmath = "0.14.1"
ash = "0.17.0"
smallvec = "0.4.1"
atomic_refcell = "0.1.0"
