[package]
name = "ngsgfx_vulkan"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ngsgfx_core = { path = "../../core" }
ngsgfx_common = { path = "../../common" }
tokenlock = { path = "../../../../support/tokenlock" }
xalloc = { path = "../../../../support/xalloc-rs", features = ["nightly"] }
cgmath = "0.15.0"
ash = "0.17.0"
smallvec = "0.4.1"
atomic_refcell = "0.1.0"
parking_lot = "0.4.4"
