[package]
name = "spirv-cross"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
libc = "0.2.7"
unsafe_unions = "0.0.2"

[build-dependencies]
gcc = "0.3"
prebuild-glslang = { path = "../../../../../tools/prebuild-glslang" }

[dev-dependencies]
include_data = { path = "../../../../../tools/include_data" }