[package]
name = "zangfx_common"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
num-integer = "0.1.34"
num-traits = "0.2.4"
cgmath = "0.16.1"
tokenlock = { path = "../../../support/tokenlock" }
metatype = "0.1.1"
