[package]
name = "ngsbase"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ngscom = { path = "../ngscom", version = "0.1" }
cgmath = "0.15.0"
num-traits = "0.1.37"

[build-dependencies]
walkdir = "1"
