cargo-features = ["edition"]

[package]
name = "zangfx_vulkan"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
zangfx_common = { path = "../../common" }
zangfx_base = { path = "../../base" }
ngsenumflags = { path = "../../../../support/ngsenumflags" }
ngsenumflags_derive = { path = "../../../../support/ngsenumflags/ngsenumflags_derive" }
parking_lot = "0.5.5"
tokenlock = { path = "../../../../support/tokenlock" }
iterpool = { path = "../../../../support/iterpool" }
refeq = { path = "../../../../support/refeq" }
xalloc = { path = "../../../../support/xalloc-rs", features = ["nightly"] }
arrayvec = "0.4.1"
ash = "0.24.3"

[dev-dependencies]
zangfx_test = { path = "../../test" }
