[package]
name = "zangfx_vulkan"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
zangfx_common = { path = "../../common" }
zangfx_base = { path = "../../base" }
ngsenumflags = { path = "../../../../support/ngsenumflags" }
ngsenumflags_derive = { path = "../../../../support/ngsenumflags/ngsenumflags_derive" }
parking_lot = "0.6"
tokenlock = { path = "../../../../support/tokenlock" }
iterpool = { path = "../../../../support/iterpool" }
refeq = { path = "../../../../support/refeq" }
xalloc = { path = "../../../../support/xalloc-rs", features = ["nightly"] }
arrayvec = "0.4.1"
ash = "0.26.2"
snowflake = "1.3.0"
lazy_static = "1.1"
smallvec = { version = "0.6.3", features = ["union"] }
itertools = "0.7.8"

[dev-dependencies]
zangfx_test = { path = "../../test" }
