[package]
name = "ngsgfx_core"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ngsenumflags = { path = "../../../support/ngsenumflags" }
ngsenumflags_derive = { path = "../../../support/ngsenumflags/ngsenumflags_derive" }
cgmath = "0.16.1"
lazy_static = "0.2"
