[package]
name = "yfft"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
num-complex = "0.1.36"
num-iter = "0.1.33"
num-traits = "0.1.37"

[target.'cfg(any(target_arch="x86", target_arch="x86_64"))'.dependencies]
immintrin = "0.2.0"
