#include "Interop/Types.idl"

[scriptable, uuid(c68f8abd-f88c-41e5-88da-956c3ca462e6)]
interface ITextCompositionEvent : nsISupports
{
    readonly attribute bstring Text;
    readonly attribute long SelectionStart;
    readonly attribute long SelectionLength;
};
