#include "Interop/Types.idl"

[scriptable, uuid(c77ded14-6119-45a4-b650-dea3f641862a)]
interface IViewport : nsISupports
{
    readonly attribute long VideoWidth;
    readonly attribute long VideoHeight;
    readonly attribute ngsFullScreenMode FullScreenMode;

    void SetVideoMode(in long videoWidth, in long videoHeight, in ngsFullScreenMode fullScreenMode);
};
