#include "nsISupports.idl"
#include "Interop/Types.idl"

#include "Backend/Common/IKeyboardEvent.idl"

[scriptable, uuid(570e1466-cd26-4363-acb8-00eb73269497)]
interface IViewportListener : nsISupports
{
    void KeyDown(in IKeyboardEvent event);
    void KeyUp(in IKeyboardEvent event);
};
