#include "Interop/Types.idl"

#include "Backend/Common/IViewportListener.idl"

[scriptable, uuid(c77ded14-6119-45a4-b650-dea3f641862a)]
interface IViewport : nsISupports
{
    void AddListener(in IViewportListener listener);
    void RemoveListener(in IViewportListener listener);

    readonly attribute long VideoWidth;
    readonly attribute long VideoHeight;
    readonly attribute ngsFullScreenMode FullScreenMode;

    readonly attribute float DevicePixelRatio;

    void SetVideoMode(in long videoWidth, in long videoHeight, in ngsFullScreenMode fullScreenMode,
        in boolean useNativePixelRatio);

    attribute boolean EnableTextInput;
    attribute ngsBox2D TextInputRectangle;
};
