//
// Copyright 2017 yvt, all rights reserved.
//
// This source code is a part of Nightingales.
//
//! NgsCOM bridges to NgsPF.
mod context;
mod nodes;

pub use ngsbase::IPresentationContext;
pub use ngsbase::ILayer;
pub use ngsbase::IWindow;
pub use ngsbase::INodeGroup;
pub use ngsbase::IWindowListener;
pub use ngsbase::IWorkspace;

pub use self::context::ComContext;
pub use self::nodes::{INodeRef, INodeRefTrait};

/// `HResult` values generated by NgsPF.
///
/// ## References
///
/// - [Structure of COM Error Codes]
///
/// [Structure of COM Error Codes]: https://msdn.microsoft.com/en-us/library/windows/desktop/ms690088(v=vs.85).aspx
///
pub mod hresults {
    use ngscom::HResult;

    /// Unable to modify a property because the node is already materialized.
    pub const E_PF_NODE_MATERIALIZED: HResult = HResult(0x80410001u32 as i32);

    /// Specified object is not a node, or originates from a different context.
    pub const E_PF_NOT_NODE: HResult = HResult(0x80410002u32 as i32);

    /// The object is currently in use by another thread.
    pub const E_PF_LOCKED: HResult = HResult(0x80410003u32 as i32);
}
