[package]
name = "ngsterrain"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
cgmath = "0.17.0"
arrayref = "0.3.4"
byteorder = "1.1.0"

[dev-dependencies]
clap = "2.26.0"
sdl2 = "0.30.0"
rand = "0.6.0"
xdispatch = { path = "../xdispatch/xdispatch" }
