[package]
name = "ngspf_core"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
arclock = { path = "../../../support/arclock" }
refeq = { path = "../../../support/refeq", features = ["nightly"] }
tokenlock = { path = "../../../support/tokenlock" }
