//
// Copyright 2017 yvt, all rights reserved.
//
// This source code is a part of Nightingales.
//
use ngsenumflags_derive::NgsEnumFlags;
use ngscom::{com_iid, com_interface};

// The contents of `$OUT_DIR/interop.rs` is generated by
// `build.rs` using `NGSRustInteropGen`
include!(concat!(env!("OUT_DIR"), "/interop.rs"));
