[package]
name = "stygian"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
arrayvec = "0.4.1"
cgmath = "0.17.0"
ngsterrain = { path = "../ngsterrain" }
num = "0.2.0"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "terrainrast"
harness = false