#pragma once
#define DISPATCH_DEBUG 0
#define USE_KEVENTS 1
#define USE_POSIX_SEM 1
#define DISPATCH_NO_LEGACY
#define HAVE_PTHREAD_WORKQUEUES 1
#define STATIC_WORKQUEUE 1
#define STATIC_KQUEUE 1
#define HAVE_PTHREAD_MAIN_NP 0
#define HAVE_GETPROGNAME 1
#define HAVE_GETEXECNAME 1
#define HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME 1
#define DISPATCH_PERF_MON 0
#define HAVE_KQUEUE_H 1
#define HAVE_LIBKQUEUE_H 1
#define HAVE_MACH_ABSOLUTE_TIME 0
#define HAVE_DECL_CLOCK_UPTIME 0
#define HAVE_DECL_CLOCK_MONOTONIC 1
#define HAVE_SYSCONF 1
#define HAVE_CRTDBG_H 1
#define HAVE_STDINT_H 1
#define HAVE_PTHREAD_H 1
#define DISPATCH_MAKEDLL
#define MAKE_STATIC 1
