[package]
name = "ysr2_localizer"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ysr2_kemar_data = { path = "kemar_data" }
ysr2_common = { path = "../common" }
yfft = { path = "../../../yfft" }
lazy_static = { version = "0.2" }
cgmath = "0.15.0"
