[package]
name = "attrtext"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
rgb = "0.7.2"
itertools = "0.7.8"
ngsenumflags = { path = "../ngsenumflags" }
ngsenumflags_derive = { path = "../ngsenumflags/ngsenumflags_derive" }
