[package]
name = "zangfx_metal"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
zangfx_common = { path = "../../common" }
zangfx_base = { path = "../../base" }
zangfx_metal-rs = { path = "src/metal-rs"}
ngsenumflags = { path = "../../../../support/ngsenumflags" }
zangfx_spirv-cross = { path = "src/spirv-cross" }
block = "0.1.5"
rspirv = "0.5.1"
spirv_headers = "1.1.5"
cocoa = "0.9"
