[package]
name = "zangfx_utils"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
zangfx_common = { path = "../common" }
zangfx_base = { path = "../base" }
flags-macro = "0.1.3"
volatile_view = { path = "../../../support/volatile_view" }
itertools = "0.7.7"
num-traits = "0.2.4"
pod = "0.5.0"
futures-preview = "0.3.0-alpha.9"
parking_lot = "0.6"
arrayvec = "0.4.1"
