[package]
name = "ngsgfx_metal"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
ngsgfx_core = { path = "../../core" }
ngsgfx_metal-rs = { path = "src/metal-rs"}
ngsgfx_common = { path = "../../common" }
spirv-cross = { path = "src/spirv-cross" }
cgmath = "0.16.1"
atomic_refcell = "0.1.0"
block = "0.1.5"
rspirv = "0.5.1"
spirv_headers = "1.1.5"
cocoa = "0.9"
