[package]
name = "alt_fp"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
packed_simd = "0.3.0"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "castf32"
harness = false