[package]
name = "ngscom"
version = "0.1.0"

authors = ["yvt <i@yvt.jp>"]
# license = "MIT"
readme = "README.md"

edition = "2018"

[dependencies]
libc = { version = "0.2.21" }
lazy_static = { version = "1.0.1" }
