[package]
name = "zangfx_utils"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]

[dependencies]
zangfx_common = { path = "../common" }
zangfx_base = { path = "../base" }
ngsenumflags = { path = "../../../support/ngsenumflags" }
itertools = "0.7.7"
