[package]
name = "ngsgamegfx"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
query_interface = "0.3.4"
futures-preview = "0.2.2"
pod = "0.5.0"
zangfx = { path = "../zangfx" }
ngspf = { path = "../ngspf" }
ngsenumflags = { path = "../support/ngsenumflags" }
injector = { path = "../support/injector" }
volatile_view = { path = "../support/volatile_view" }

[dev-dependencies]
cgmath = "0.16.1"
refeq = { path = "../support/refeq" }